### ISSUE TITLE
f# ionide plugin vscode

### ISSUE THREAD

**Issue by devosalain** [sec/dotnet-core-freebsd-source-build#17]
f# ionide plugin for vscode does not work.

**Comment by sec** [comment]
Can you provide more details - this sentence doesn't really tells me anything? :)

**Comment by devosalain** [comment]
I'm sorry. Using vscode with F#/ionide plugin works fine on Gentoo-Linux or Ubuntu-Linux. 
On FreeBSD it works half. In the editor function signatures are not given.
PS: Thanks for making the builds. But on FreeBSD it would be nice to have a "dotnet-sdk-6.0" or "dotnet-sdk-7.0" package as I have on Ubuntu. Meaning one "pkg install" to install everything.

**Comment by sec** [comment]
There's no offical support for .NET under FreeBSD - so there's no easy way to `pkg install` :)
You have to download binaries, extract it to ex. `/usr/local/share/dotnet` and add that to PATH (either your local user or global profile), so that you'll have `dotnet` available system/user wide.

Can you provide some error/logs from VSCode console/debug/output/something?

**Comment by sec** [comment]
Closing this as it's not related to .NET build directly.
